survwey/survwey/src/main/java/mcnc/survwey/global/exception/CustomException.java, survwey/survwey/src/main/java/mcnc/survwey/global/exception/CustomExceptionInterceptor.java, survwey/survwey/src/main/java/mcnc/survwey/global/exception/ErrorCode.java, survwey/survwey/src/main/java/mcnc/survwey/global/exception/ErrorDTO.java
=> feat: 커스텀 예외 로직 작성

survwey/survwey/src/main/java/mcnc/survwey/api/authentication/controller/AuthController.java, survwey/survwey/src/main/java/mcnc/survwey/api/authentication/controller/LoginController.java, survwey/survwey/src/main/java/mcnc/survwey/api/authentication/dto/AuthDTO.java, survwey/survwey/src/main/java/mcnc/survwey/api/authentication/service/AuthService.java, survwey/survwey/src/main/java/mcnc/survwey/api/authentication/service/LoginService.java, survwey/survwey/src/main/java/mcnc/survwey/domain/user/User.java, survwey/survwey/src/main/java/mcnc/survwey/domain/user/UserRepository.java, survwey/survwey/src/main/java/mcnc/survwey/domain/user/UserService.java, survwey/survwey/src/main/java/mcnc/survwey/global/config/SecurityConfig.java, survwey/survwey/src/main/resources/application.properties
- PasswordEncoder 빈 등록
- Security Config 기본 설정
- 기본 디렉토리 구조 작성(회원가입/로그인)
=> Spring Security 기본 설정 및 Base 디렉토리 구조 작성

.idea/.gitignore, .idea/MCNC_Backend.iml, .idea/compiler.xml, .idea/gradle.xml, .idea/jarRepositories.xml, .idea/misc.xml, .idea/modules.xml, .idea/vcs.xml, survwey/survwey/src/main/java/mcnc/survwey/api/authentication/dto/AuthDTO.java
=> feat: test

survwey/survwey/.gitignore
- gitIgnore에 application.properties 추가하여 개인 DB로 개발
=> refactor: gitignore에 application.properties 추가

survwey/survwey/src/main/java/mcnc/survwey/domain/enums/Gender.java, survwey/survwey/src/main/java/mcnc/survwey/domain/objAnswer/ObjAnswer.java, survwey/survwey/src/main/java/mcnc/survwey/domain/question/Question.java, survwey/survwey/src/main/java/mcnc/survwey/domain/questionType/QuestionType.java, survwey/survwey/src/main/java/mcnc/survwey/domain/selection/Selection.java, survwey/survwey/src/main/java/mcnc/survwey/domain/selection/SelectionId.java, survwey/survwey/src/main/java/mcnc/survwey/domain/subjAnswer/SubjAnswer.java, survwey/survwey/src/main/java/mcnc/survwey/domain/survey/Survey.java, survwey/survwey/src/main/java/mcnc/survwey/domain/user/User.java, survwey/survwey/src/main/resources/application.properties
데이터베이스 스키마에 맞춘 엔티티 생성
- user
- survey
- subjAnswer
- objAnswer
- selection
- questionType
- question
및 Enum 생성
=> feat: 데이터베이스 스키마에 맞춘 엔티티 생성

survwey/survwey/src/main/java/mcnc/survwey/api/authentication/controller/AuthController.java, survwey/survwey/src/main/java/mcnc/survwey/api/authentication/dto/ChangePasswordDTO.java, survwey/survwey/src/main/java/mcnc/survwey/api/authentication/dto/ModifyDTO.java, survwey/survwey/src/main/java/mcnc/survwey/api/authentication/service/AuthService.java, survwey/survwey/src/test/java/mcnc/survwey/api/authentication/service/AuthServiceTest.java
=> feat: 프로필 수정 기능 개발

survwey/survwey/src/test/java/mcnc/survwey/api/authentication/service/AuthServiceTest.java
-회원 가입 테스트 로직 일부 수정
-프로필 수정 테스트
=> feat: 회원가입, 프로필 수정 단위 테스트 작성

survwey/survwey/.gitignore, survwey/survwey/build.gradle, survwey/survwey/src/main/java/mcnc/survwey/SurvweyApplication.java, survwey/survwey/src/main/resources/application.properties
=> feat: application.properties 데이터베이스 설정 암호화

survwey/survwey/src/main/java/mcnc/survwey/api/survey/controller/SurveyInquiryController.java, survwey/survwey/src/main/java/mcnc/survwey/api/survey/dto/UserCreatedSurveyDTO.java, survwey/survwey/src/main/java/mcnc/survwey/api/survey/service/SurveyInquiryService.java, survwey/survwey/src/main/java/mcnc/survwey/domain/survey/Survey.java, survwey/survwey/src/main/java/mcnc/survwey/domain/survey/SurveyRepository.java
=> feat: 본인이 생성한 설문 리스트 조회 로직 작성

survwey/survwey/src/main/java/mcnc/survwey/api/survey/controller/SurveyInquiryController.java, survwey/survwey/src/main/java/mcnc/survwey/domain/objAnswer/ObjAnswer.java, survwey/survwey/src/main/java/mcnc/survwey/domain/respond/Respond.java, survwey/survwey/src/main/java/mcnc/survwey/domain/subjAnswer/SubjAnswer.java, survwey/survwey/src/main/java/mcnc/survwey/domain/survey/Survey.java, survwey/survwey/src/main/java/mcnc/survwey/domain/user/User.java, survwey/survwey/src/main/java/mcnc/survwey/domain/user/UserRepository.java, survwey/survwey/src/main/java/mcnc/survwey/domain/user/UserService.java, survwey/survwey/src/main/java/mcnc/survwey/global/exception/custom/ErrorCode.java
- Respond 테이블 생성
- User 테이블의 기본키를 UserId로 수정
- User 엔티티와 연관된 연관관계 수정
- User 공통 메서드 수정
=> feat: Respond 테이블 생성 및 User 기본키 변경

survwey/survwey/src/main/java/mcnc/survwey/api/authentication/controller/AuthController.java, survwey/survwey/src/main/java/mcnc/survwey/api/authentication/dto/AuthDTO.java, survwey/survwey/src/main/java/mcnc/survwey/api/authentication/dto/ChangePasswordDTO.java, survwey/survwey/src/main/java/mcnc/survwey/api/authentication/dto/ModifyDTO.java, survwey/survwey/src/main/java/mcnc/survwey/api/authentication/service/AuthService.java, survwey/survwey/src/main/java/mcnc/survwey/api/survey/controller/SurveySearchController.java, survwey/survwey/src/main/java/mcnc/survwey/api/survey/dto/SearchDTO.java, survwey/survwey/src/main/java/mcnc/survwey/api/survey/dto/SurveyModifyDTO.java, survwey/survwey/src/main/java/mcnc/survwey/api/survey/service/SurveyModifyService.java, survwey/survwey/src/main/java/mcnc/survwey/api/survey/service/SurveySearchService.java, survwey/survwey/src/main/java/mcnc/survwey/domain/survey/SurveyRepository.java, survwey/survwey/src/main/java/mcnc/survwey/global/exception/custom/ErrorCode.java, survwey/survwey/src/test/java/mcnc/survwey/api/authentication/service/AuthServiceTest.java
-회원가입, 프로필 수정, 비밀번호 변경 로직 수정
-설문 검색 기능 추가
-에러 코드 아이디 중복, 이메일 중복 추가
=> feat: 회원가입, 비밀번호 변경, 프로필 수정 로직 수정 및 설문 검색 기능 추가

survwey/survwey/src/main/java/mcnc/survwey/api/authentication/service/AuthService.java, survwey/survwey/src/main/java/mcnc/survwey/domain/user/UserRepository.java
=> feat: 이메일 중복 체크 부분 수정

survwey/survwey/src/main/java/mcnc/survwey/api/survey/controller/SurveyModifyController.java, survwey/survwey/src/main/java/mcnc/survwey/api/survey/controller/SurveySearchController.java, survwey/survwey/src/main/java/mcnc/survwey/api/survey/dto/SearchDTO.java, survwey/survwey/src/main/java/mcnc/survwey/api/survey/dto/SurveyDTO.java, survwey/survwey/src/main/java/mcnc/survwey/api/survey/service/SurveyModifyService.java, survwey/survwey/src/main/java/mcnc/survwey/api/survey/service/SurveySearchService.java, survwey/survwey/src/main/java/mcnc/survwey/domain/respond/RespondRepository.java, survwey/survwey/src/main/java/mcnc/survwey/domain/respond/RespondService.java, survwey/survwey/src/main/java/mcnc/survwey/domain/survey/SurveyRepository.java
-github 레포지토리 변경 
-설문 검색 로직 수정 완료
-설문 레포지토리 이름 변경
=> feat: gitHub 레포지토리 변경 후 문제있던 설문 검색 로직 수정

survwey/survwey/src/main/java/mcnc/survwey/api/survey/controller/SurveySearchController.java, survwey/survwey/src/main/java/mcnc/survwey/api/survey/dto/SurveyDTO.java, survwey/survwey/src/main/java/mcnc/survwey/api/survey/dto/SurveyInfoDTO.java, survwey/survwey/src/main/java/mcnc/survwey/api/survey/service/SurveyModifyService.java
-설문 검색 결과 데이터 형식 변경
-SurveyInfoDTO 추가
=> feat: front의 데이터형식으로 변경

survwey/survwey/src/main/java/mcnc/survwey/api/survey/controller/SurveyInquiryController.java, survwey/survwey/src/main/java/mcnc/survwey/api/survey/controller/SurveyManageController.java, survwey/survwey/src/main/java/mcnc/survwey/api/survey/dto/QuestionDTO.java, survwey/survwey/src/main/java/mcnc/survwey/api/survey/dto/ResponseDTO.java, survwey/survwey/src/main/java/mcnc/survwey/api/survey/dto/SelectionDTO.java, survwey/survwey/src/main/java/mcnc/survwey/api/survey/dto/SurveyResponseDTO.java, survwey/survwey/src/main/java/mcnc/survwey/api/survey/dto/SurveyWithDetailDTO.java, survwey/survwey/src/main/java/mcnc/survwey/api/survey/service/SurveyManageService.java, survwey/survwey/src/main/java/mcnc/survwey/domain/enums/QuestionType.java, survwey/survwey/src/main/java/mcnc/survwey/domain/objAnswer/ObjAnswer.java, survwey/survwey/src/main/java/mcnc/survwey/domain/objAnswer/ObjAnswerRepository.java, survwey/survwey/src/main/java/mcnc/survwey/domain/objAnswer/ObjAnswerService.java, survwey/survwey/src/main/java/mcnc/survwey/domain/question/QuestionService.java, survwey/survwey/src/main/java/mcnc/survwey/domain/respond/Respond.java, survwey/survwey/src/main/java/mcnc/survwey/domain/respond/RespondService.java, survwey/survwey/src/main/java/mcnc/survwey/domain/selection/SelectionService.java, survwey/survwey/src/main/java/mcnc/survwey/domain/subjAnswer/SubjAnswer.java, survwey/survwey/src/main/java/mcnc/survwey/domain/subjAnswer/SubjAnswerRepository.java, survwey/survwey/src/main/java/mcnc/survwey/domain/subjAnswer/SubjAnswerService.java, survwey/survwey/src/main/java/mcnc/survwey/domain/survey/SurveyService.java, survwey/survwey/src/main/java/mcnc/survwey/global/exception/custom/ErrorCode.java
- 설문 상세 조회 시 제작자 아이디도 반환하도록 수정
- 설문 응답 로직 작성
- Entity -> DTO, DTO -> Entity 메서드 작성
- 단일 책임 원칙에 의거하여 코드 리펙토링
=> feat: 설문 응답 로직 및 코드 리펙토링

survwey/survwey/src/main/java/mcnc/survwey/api/survey/controller/SurveyModifyController.java, survwey/survwey/src/main/java/mcnc/survwey/api/survey/controller/SurveySearchController.java, survwey/survwey/src/main/java/mcnc/survwey/api/survey/dto/SurveyModifyDTO.java, survwey/survwey/src/main/java/mcnc/survwey/api/survey/dto/SurveyModifyWithDetailDTO.java, survwey/survwey/src/main/java/mcnc/survwey/api/survey/service/SurveyInquiryService.java, survwey/survwey/src/main/java/mcnc/survwey/api/survey/service/SurveyModifyService.java, survwey/survwey/src/main/java/mcnc/survwey/api/survey/service/SurveySearchService.java, survwey/survwey/src/main/java/mcnc/survwey/domain/respond/RespondRepository.java, survwey/survwey/src/main/java/mcnc/survwey/domain/respond/RespondService.java, survwey/survwey/src/main/java/mcnc/survwey/domain/survey/SurveyRepository.java, survwey/survwey/src/main/java/mcnc/survwey/domain/survey/SurveyService.java, survwey/survwey/src/main/java/mcnc/survwey/global/exception/custom/ErrorCode.java
=> feat: 설문 수정 로직 삭제 후 재등록으로 변경, 충돌 문제 해결, 에러코드 추가

survwey/survwey/src/main/java/mcnc/survwey/domain/user/controller/AuthController.java, survwey/survwey/src/main/java/mcnc/survwey/global/config/WebConfig.java
-URL 매핑경로 재설정
-WebConfi 경로제외 패턴 수정
=> feat: AuthController URL 매핑경로 재설정 및 WebConfig 경로제외 패턴 수정

survwey/survwey/build.gradle, survwey/survwey/src/main/java/mcnc/survwey/domain/survey/inquiry/controller/SurveyInquiryController.java, survwey/survwey/src/main/java/mcnc/survwey/domain/survey/inquiry/service/SurveyInquiryService.java, survwey/survwey/src/main/java/mcnc/survwey/domain/survey/manage/controller/SurveyManageController.java, survwey/survwey/src/main/java/mcnc/survwey/domain/user/controller/AuthController.java, survwey/survwey/src/main/java/mcnc/survwey/global/config/SwaggerConfig.java, survwey/survwey/src/main/java/mcnc/survwey/global/config/WebConfig.java
- Swagger 의존성 추가
- 설문 조회 Swagger 명세서 작성
- 설문 관리 Swagger 명세서 작성
- SwaggerConfig 생성
=> feat: Swagger 추가 및 명세서 작성

survwey/survwey/src/main/java/mcnc/survwey/domain/survey/common/repository/SurveyRepository.java, survwey/survwey/src/main/java/mcnc/survwey/domain/survey/inquiry/controller/SurveyInquiryController.java, survwey/survwey/src/main/java/mcnc/survwey/domain/survey/inquiry/service/SurveyInquiryService.java
=> feat: 사용자 참여한 설문 검색 로직

survwey/survwey/src/main/java/mcnc/survwey/domain/selection/Selection.java, survwey/survwey/src/main/java/mcnc/survwey/domain/survey/common/dto/SelectionDTO.java, survwey/survwey/src/main/java/mcnc/survwey/domain/survey/manage/service/SurveyManageService.java, survwey/survwey/src/main/java/mcnc/survwey/global/config/WebConfig.java, survwey/survwey/src/main/java/mcnc/survwey/global/exception/custom/ErrorCode.java
- 데이터베이스 isEtc 컬럼 추가에 따른 Entity 수정
- 이에 영향 받는 비즈니스 로직 수정
- 만료일이 지난 설문 응답 못하도록 수정
- WebConfig 세션 무시 URL 수정
=> feat: 기타(보기) 컬럼 추가에 따른 변경 및 만료일이 지난 설문 응답 못하도록 수정

survwey/survwey/src/main/java/mcnc/survwey/domain/respond/service/RespondService.java, survwey/survwey/src/main/java/mcnc/survwey/domain/survey/inquiry/controller/SurveyInquiryController.java, survwey/survwey/src/main/java/mcnc/survwey/domain/survey/inquiry/service/SurveyInquiryService.java, survwey/survwey/src/main/java/mcnc/survwey/domain/survey/manage/controller/SurveyManageController.java, survwey/survwey/src/main/java/mcnc/survwey/domain/survey/manage/service/SurveyManageService.java, survwey/survwey/src/main/java/mcnc/survwey/domain/user/controller/AuthController.java, survwey/survwey/src/main/java/mcnc/survwey/global/exception/custom/ErrorCode.java
-각 Controller Swagger 주석 추가 및 에러코드 처리 문서화
=> docs: Controller에 Swagger 주석 추가 및 에러 코드 처리 문서화

survwey/survwey/src/main/java/mcnc/survwey/domain/survey/manage/service/SurveyManageService.java
=> feat: 만료일과 LocaDateTime이 같을 때도 설문 만료로 수정

survwey/survwey/src/main/java/mcnc/survwey/domain/survey/common/Survey.java, survwey/survwey/src/main/java/mcnc/survwey/domain/survey/manage/controller/SurveyManageController.java, survwey/survwey/src/main/java/mcnc/survwey/domain/survey/manage/dto/SurveyExpirationDTO.java, survwey/survwey/src/main/java/mcnc/survwey/domain/survey/manage/service/SurveyManageService.java, survwey/survwey/src/main/java/mcnc/survwey/global/exception/custom/ErrorCode.java
-Controller Swagger 주석 및 에러코드 작성
-설문 강제 종료 로직 작성
=> feat: 설문 강제 종료 로직 작성,  Controller Swagger 주석 및 에러 코드 처리 문서화

survwey/survwey/src/main/java/mcnc/survwey/domain/survey/manage/controller/SurveyManageController.java
=> feat: 설문 강제 종료 PathVariable로 수정

survwey/survwey/src/main/java/mcnc/survwey/domain/user/controller/AuthController.java, survwey/survwey/src/main/java/mcnc/survwey/domain/user/service/AuthService.java, survwey/survwey/src/main/java/mcnc/survwey/global/config/WebConfig.java
-UserId, Email 중복 체크 Service, Controller  추가
=> feat: 회원가입 UserId, Email 중복 체크 로직 작성

.idea/compiler.xml, survwey/survwey/build.gradle, survwey/survwey/src/main/java/mcnc/survwey/domain/question/dto/SurveyResultMapper.java, survwey/survwey/src/main/java/mcnc/survwey/domain/question/repository/QuestionRepository.java, survwey/survwey/src/main/java/mcnc/survwey/domain/question/repository/queryDSL/QuestionRepositoryCustom.java, survwey/survwey/src/main/java/mcnc/survwey/domain/question/repository/queryDSL/QuestionRepositoryImpl.java, survwey/survwey/src/main/java/mcnc/survwey/domain/survey/common/repository/SurveyRepository.java, survwey/survwey/src/main/java/mcnc/survwey/domain/survey/common/repository/queryDSL/SurveyRepositoryCustom.java, survwey/survwey/src/main/java/mcnc/survwey/domain/survey/common/repository/queryDSL/SurveyRepositoryImpl.java, survwey/survwey/src/main/java/mcnc/survwey/global/config/QueryDSLConfig.java, survwey/survwey/src/main/java/mcnc/survwey/global/config/SecurityConfig.java
- QueryDSL 의존성 추가 및 적용
- 설문 DB 쿼리 QueryDSL로 변경
- 질문 DB 쿼리 QueryDSL로 변경
- FrontEnd 임시 배포용 URL CORS 허용
=> refactor: QueryDSL 의존성 추가 및 기존 Native Query QueryDSL로 변경

.idea/compiler.xml, survwey/survwey/.gitignore, survwey/survwey/build.gradle, survwey/survwey/src/main/java/mcnc/survwey/SurvweyApplication.java, survwey/survwey/src/main/java/mcnc/survwey/domain/mail/MailController.java, survwey/survwey/src/main/java/mcnc/survwey/domain/mail/MailDTO.java, survwey/survwey/src/main/java/mcnc/survwey/domain/mail/MailService.java, survwey/survwey/src/main/resources/application.properties, survwey/survwey/src/main/resources/templates/mail/send.html
-이메일 링크 전송 Service, Controller 작성
-gitignore idea 추가
-application.properties 충돌 해결
=> feat: 이메일 링크 전송 로직 작성 및 gitignore에 idea 추가, application.properties 충돌 해결

survwey/survwey/src/main/java/mcnc/survwey/SurvweyApplication.java, survwey/survwey/src/main/java/mcnc/survwey/domain/mail/controller/MailController.java, survwey/survwey/src/main/java/mcnc/survwey/domain/mail/service/MailService.java, survwey/survwey/src/main/java/mcnc/survwey/domain/mail/utils/EncryptionUtil.java, survwey/survwey/src/main/java/mcnc/survwey/domain/user/controller/AuthController.java, survwey/survwey/src/main/resources/application.properties
=> feat: 링크 암호화 로직 수정

survwey/survwey/src/main/java/mcnc/survwey/domain/mail/controller/MailController.java, survwey/survwey/src/main/java/mcnc/survwey/domain/mail/service/MailService.java, survwey/survwey/src/main/java/mcnc/survwey/domain/mail/utils/EncryptionUtil.java
-만료일 경과 시 error 메시지
-Swagger 추가
-log 제거
=> feat: 이메일 전송 시 만료일이 지나면 error메시지 추가, Swagger추가

survwey/survwey/src/main/java/mcnc/survwey/domain/survey/common/repository/SurveyRepository.java, survwey/survwey/src/main/java/mcnc/survwey/domain/survey/inquiry/controller/SurveyInquiryController.java, survwey/survwey/src/main/java/mcnc/survwey/domain/survey/inquiry/service/SurveyInquiryService.java
-설문 전체 검색
-사용자가 생성한 설문 검색
-사용자가 참여한 설문 검색
-충돌 해결
=> feat: 설문 전체 검색, 사용자가 생성한 설문 검색, 사용자가 참여한 설문 검색으로 구분, 충돌 해결

survwey/survwey/src/main/java/mcnc/survwey/domain/survey/inquiry/controller/SurveyInquiryController.java
=> feat: SurveyInquiryController에 surveySearch 메소드 Swagger 수정

survwey/survwey/src/main/java/mcnc/survwey/domain/user/controller/AccountController.java, survwey/survwey/src/main/java/mcnc/survwey/domain/user/dto/ModifyDTO.java, survwey/survwey/src/main/java/mcnc/survwey/domain/user/service/AccountService.java
=> feat: 프로필 조회 구현

survwey/survwey/src/main/java/mcnc/survwey/domain/mail/service/MailService.java, survwey/survwey/src/main/java/mcnc/survwey/domain/respond/service/RespondService.java, survwey/survwey/src/main/java/mcnc/survwey/domain/survey/response/controller/SurveyResponseController.java, survwey/survwey/src/main/java/mcnc/survwey/domain/survey/response/service/SurveyResponseService.java, survwey/survwey/src/main/java/mcnc/survwey/global/exception/custom/ErrorCode.java
- 이미 설문에 응답한 경우 응답 못하도록 수정
- Swagger 작성
- 오탈자 처리
=> feat: 중복 응답 방지 로직 작성 및 예외, 오류 처리

survwey/survwey/src/main/java/mcnc/survwey/domain/mail/controller/MailController.java, survwey/survwey/src/main/java/mcnc/survwey/domain/mail/service/MailService.java, survwey/survwey/src/main/java/mcnc/survwey/domain/mail/utils/EncryptionUtil.java, survwey/survwey/src/main/java/mcnc/survwey/domain/user/controller/AccountController.java, survwey/survwey/src/main/java/mcnc/survwey/global/config/WebConfig.java
=> feat: 메일 전송 수정

survwey/survwey/src/main/java/mcnc/survwey/domain/objAnswer/service/ObjAnswerService.java, survwey/survwey/src/main/java/mcnc/survwey/domain/question/repository/QuestionRepository.java, survwey/survwey/src/main/java/mcnc/survwey/domain/question/repository/queryDSL/QuestionRepositoryImpl.java, survwey/survwey/src/main/java/mcnc/survwey/domain/respond/service/RespondService.java, survwey/survwey/src/main/java/mcnc/survwey/domain/subjAnswer/service/SubjAnswerService.java, survwey/survwey/src/main/java/mcnc/survwey/domain/survey/common/service/SurveyService.java, survwey/survwey/src/main/java/mcnc/survwey/domain/survey/inquiry/service/SurveyInquiryService.java, survwey/survwey/src/main/java/mcnc/survwey/domain/survey/manage/service/SurveyManageService.java, survwey/survwey/src/main/java/mcnc/survwey/domain/survey/response/service/SurveyResponseService.java, survwey/survwey/src/main/java/mcnc/survwey/domain/user/service/AuthService.java, survwey/survwey/src/main/java/mcnc/survwey/domain/user/service/UserService.java, survwey/survwey/src/main/java/mcnc/survwey/global/config/AuthInterceptor.java, survwey/survwey/src/main/java/mcnc/survwey/global/config/WebConfig.java, survwey/survwey/src/main/java/mcnc/survwey/global/exception/global/GlobalExceptionHandler.java
- 아래에 해당하는 관련 클래스에 주석 추가
- 설문
- 질문
- 보기
- 객관식 응답
- 주관식 응답
- 사용자
- 커스텀 예외
- 세션 인터셉터
=> refactor: 작성한 전체 코드 주석 작성

survwey/survwey/build.gradle, survwey/survwey/src/main/java/mcnc/survwey/domain/survey/common/dto/SurveyDTO.java, survwey/survwey/src/main/java/mcnc/survwey/domain/survey/manage/service/SurveyManageService.java, survwey/survwey/src/main/java/mcnc/survwey/domain/survey/response/controller/SurveyResponseController.java, survwey/survwey/src/main/java/mcnc/survwey/global/exception/custom/ErrorCode.java, survwey/survwey/src/main/java/mcnc/survwey/global/redis/RedisConfig.java, survwey/survwey/src/main/java/mcnc/survwey/global/redis/RedisService.java, survwey/survwey/src/main/resources/application.properties
- Redis 설정
- Redis 키 등록/삭제/즉시 만료 로직 작성
- Redis 키에 대한 유효성 검사 로직 추가
- 설문 Controller 유효성 검사 추가
=> feat: 이메일 알림을 위한 Redis 적용

survwey/survwey/src/main/java/mcnc/survwey/SurvweyApplication.java, survwey/survwey/src/main/java/mcnc/survwey/domain/mail/controller/MailController.java, survwey/survwey/src/main/java/mcnc/survwey/domain/mail/service/MailService.java, survwey/survwey/src/main/java/mcnc/survwey/global/redis/RedisConfig.java, survwey/survwey/src/main/resources/application.properties
=> refactor: MailService 리팩토링

survwey/survwey/build.gradle, survwey/survwey/src/main/java/mcnc/survwey/domain/mail/service/MailService.java, survwey/survwey/src/main/java/mcnc/survwey/domain/survey/inquiry/controller/SurveyInquiryController.java, survwey/survwey/src/main/java/mcnc/survwey/domain/user/controller/AccountController.java, survwey/survwey/src/main/java/mcnc/survwey/domain/user/service/AccountService.java
=> feat: 전체 리팩토링

survwey/survwey/src/main/java/mcnc/survwey/domain/user/controller/AccountController.java, survwey/survwey/src/main/java/mcnc/survwey/domain/user/dto/ProfileDTO.java, survwey/survwey/src/main/java/mcnc/survwey/domain/user/dto/ProfileModifyDTO.java, survwey/survwey/src/main/java/mcnc/survwey/domain/user/service/AccountService.java, survwey/survwey/src/test/java/mcnc/survwey/api/authentication/service/AccountServiceTest.java
-ProfileDTO, ProfileModfiyDTO 추가
-ModifyDTO 삭제
-프로필 관련 service 로직 변경
=> feat: 프로필 수정 및 조회 변경

survwey/survwey/src/main/java/mcnc/survwey/domain/user/controller/AccountController.java, survwey/survwey/src/main/java/mcnc/survwey/domain/user/service/AccountService.java
=> feat: front 에서 Profile 수정 DB에 반영안되던거 수정

survwey/survwey/src/main/java/mcnc/survwey/domain/mail/controller/MailController.java, survwey/survwey/src/main/java/mcnc/survwey/domain/survey/common/dto/SurveyDTO.java, survwey/survwey/src/main/java/mcnc/survwey/domain/survey/common/service/SurveyRedisService.java, survwey/survwey/src/main/java/mcnc/survwey/domain/survey/manage/controller/SurveyManageController.java, survwey/survwey/src/main/java/mcnc/survwey/domain/survey/manage/service/SurveyManageService.java, survwey/survwey/src/main/java/mcnc/survwey/domain/user/controller/AccountController.java, survwey/survwey/src/main/java/mcnc/survwey/domain/user/controller/AuthController.java, survwey/survwey/src/main/java/mcnc/survwey/domain/user/dto/EmailSendDTO.java, survwey/survwey/src/main/java/mcnc/survwey/domain/user/dto/ProfileModifyDTO.java, survwey/survwey/src/main/java/mcnc/survwey/domain/user/service/UserRedisService.java, survwey/survwey/src/main/java/mcnc/survwey/global/exception/custom/CustomException.java, survwey/survwey/src/main/java/mcnc/survwey/global/exception/custom/CustomExceptionInterceptor.java, survwey/survwey/src/main/java/mcnc/survwey/global/exception/custom/ErrorCode.java, survwey/survwey/src/main/java/mcnc/survwey/global/exception/global/GlobalExceptionHandler.java
- UserRedisService 주석 추가 및 리펙토링
- SurveyRedisService 주석 추가 및 리펙토링
- 기타 주석 작성
- CustomException 로그 및 생성자 수정
- 프로필 수정, 이메일 인증 DTO에 유효성 검증 추가
=> refactor: 주석 및 유효성 검증 추가

survwey/survwey/.gitignore, survwey/survwey/build.gradle, survwey/survwey/src/main/java/mcnc/survwey/SurvweyApplication.java, survwey/survwey/src/main/java/mcnc/survwey/domain/objAnswer/ObjAnswer.java, survwey/survwey/src/main/java/mcnc/survwey/domain/question/Question.java, survwey/survwey/src/main/java/mcnc/survwey/domain/respond/Respond.java, survwey/survwey/src/main/java/mcnc/survwey/domain/selection/Selection.java, survwey/survwey/src/main/java/mcnc/survwey/domain/selection/SelectionId.java, survwey/survwey/src/main/java/mcnc/survwey/domain/subjAnswer/SubjAnswer.java, survwey/survwey/src/main/java/mcnc/survwey/domain/survey/common/Survey.java, survwey/survwey/src/main/java/mcnc/survwey/domain/survey/manage/service/SurveyManageService.java, survwey/survwey/src/main/java/mcnc/survwey/domain/survey/response/controller/SurveyResponseController.java, survwey/survwey/src/main/java/mcnc/survwey/domain/survey/response/service/SurveyResponseService.java, survwey/survwey/src/main/java/mcnc/survwey/domain/user/User.java, survwey/survwey/src/main/java/mcnc/survwey/global/config/CacheConfig.java, survwey/survwey/src/test/java/mcnc/survwey/SurvweyApplicationTests.java, survwey/survwey/src/test/java/mcnc/survwey/user/service/AccountServiceTest.java
- 스프링 자체 캐싱 적용
- Entity 리펙토링
- 테스트 코드 기반 작성
=> feat: 스프링 캐시 적용 및 리펙토링

survwey/survwey/src/main/java/mcnc/survwey/SurvweyApplication.java, survwey/survwey/src/main/java/mcnc/survwey/domain/mail/controller/MailController.java, survwey/survwey/src/main/java/mcnc/survwey/domain/mail/service/MailService.java, survwey/survwey/src/main/java/mcnc/survwey/domain/user/controller/AccountController.java, survwey/survwey/src/main/java/mcnc/survwey/domain/user/service/UserService.java, survwey/survwey/src/main/java/mcnc/survwey/global/exception/custom/ErrorCode.java
-설문 초대 메일 서비스 단체 전송으로 수정
-설문 초대 메일 컨트롤러  @RequestBody Map<String, List<String>> 추가
=> "feat: 설문 초대 메일 단체 전송으로 수정"

survwey/survwey/src/main/java/mcnc/survwey/domain/mail/controller/MailController.java, survwey/survwey/src/main/java/mcnc/survwey/domain/mail/service/MailService.java, survwey/survwey/src/main/java/mcnc/survwey/domain/mail/utils/EncryptionUtil.java, survwey/survwey/src/main/java/mcnc/survwey/domain/survey/inquiry/controller/SurveyInquiryController.java, survwey/survwey/src/main/java/mcnc/survwey/domain/user/controller/AccountController.java, survwey/survwey/src/main/java/mcnc/survwey/domain/user/service/AccountService.java
-MailService 메소드 이름 변경
-MailController 메소드 이름 변경
-EncryptionUtil 공통 로직 메소드화, 메소드 이름 변경
=> refactor: Mail Service, Controller, Util 구조 및 메소드 이름 등 리팩토링

survwey/survwey/src/main/java/mcnc/survwey/domain/mail/controller/MailController.java, survwey/survwey/src/main/java/mcnc/survwey/domain/survey/common/repository/SurveyRepository.java, survwey/survwey/src/main/java/mcnc/survwey/domain/survey/common/repository/queryDSL/SurveyRepositoryImpl.java, survwey/survwey/src/main/java/mcnc/survwey/domain/survey/inquiry/controller/SurveyInquiryController.java, survwey/survwey/src/main/java/mcnc/survwey/domain/survey/inquiry/service/SurveyInquiryService.java, survwey/survwey/src/main/java/mcnc/survwey/domain/user/controller/AccountController.java, survwey/survwey/src/main/java/mcnc/survwey/domain/user/controller/AuthController.java, survwey/survwey/src/main/java/mcnc/survwey/domain/user/service/AccountService.java, survwey/survwey/src/test/java/mcnc/survwey/user/service/SurveyInquiryTest.java
- 본인이 만든 설문인지 확인 로직 작성
- 설문 조회 페이징 쿼리에 전체 개수 추가
- 설문 조회 테스트 코드 일부 작성
- 리펙토링
=> feat: 본인이 만든 설문 확인 로직, 설문 조회 페이징 쿼리에 전체 개수 추가

survwey/survwey/build.gradle, survwey/survwey/src/main/java/mcnc/survwey/api/survey/inquiry/controller/SurveyInquiryController.java, survwey/survwey/src/main/java/mcnc/survwey/api/survey/manage/service/SurveyManageService.java, survwey/survwey/src/main/java/mcnc/survwey/domain/question/repository/QuestionRepository.java, survwey/survwey/src/main/java/mcnc/survwey/domain/question/service/QuestionService.java, survwey/survwey/src/main/java/mcnc/survwey/domain/selection/service/SelectionService.java, survwey/survwey/src/main/java/mcnc/survwey/domain/survey/Survey.java, survwey/survwey/src/main/java/mcnc/survwey/domain/survey/repository/queryDSL/SurveyRepositoryImpl.java, survwey/survwey/src/main/java/mcnc/survwey/domain/survey/service/SurveyRedisService.java, survwey/survwey/src/main/java/mcnc/survwey/domain/survey/service/SurveyService.java
- 수정 시 설문 아이디가 변경되는 오류 수정
- 설문 생성한 설문, 응답한 설문 검색 등에서 Controller가 파라미터를 인식 못하는 오류 수정
=> fix: 설문 수정 로직 및 설문 조회 오류 수정

survwey/survwey/src/main/java/mcnc/survwey/api/survey/inquiry/controller/SurveyInquiryController.java, survwey/survwey/src/main/java/mcnc/survwey/api/survey/inquiry/service/SurveyInquiryService.java, survwey/survwey/src/main/java/mcnc/survwey/api/survey/response/service/AnsweredSurveyService.java, survwey/survwey/src/main/java/mcnc/survwey/domain/survey/repository/SurveyRepository.java, survwey/survwey/src/main/java/mcnc/survwey/domain/survey/repository/queryDSL/SurveyRepositoryCustom.java, survwey/survwey/src/main/java/mcnc/survwey/domain/survey/repository/queryDSL/SurveyRepositoryImpl.java, survwey/survwey/src/main/java/mcnc/survwey/global/exception/global/GlobalExceptionHandler.java, survwey/survwey/src/main/java/mcnc/survwey/global/utils/EncryptionUtil.java, survwey/survwey/src/test/java/mcnc/survwey/survey/SurveyInquiryTest.java
- 응답한 설문 리스트 조회 정렬 기준 수정
- 전체 설문 검색 참여 가능한 설문 검색으로 변경
- 설문 검색 공백 제거
- 응답한 설문 정렬 기준 변경
=> feat: 설문 검색 로직 및 정렬 기준 변경

survwey/survwey/src/test/java/mcnc/survwey/user/service/AuthServiceTest.java
=> feat: AuthService Test코드 작성

survwey/survwey/src/test/java/mcnc/survwey/user/service/AuthServiceTest.java
Reverts MCNC-Internship-Project/Backend#81
=> Revert "feat: AuthService Test코드 작성"

survwey/survwey/src/test/java/mcnc/survwey/user/service/AuthServiceTest.java
=> feat: AuthService Test 코드 작성

survwey/survwey/src/test/java/mcnc/survwey/user/service/AuthServiceTest.java
-비밀번호 변경 인증번호 체크 실패 케이스 테스트 코드 수정
=> feat: AuthService Test 수정

survwey/survwey/src/main/java/mcnc/survwey/api/survey/inquiry/controller/SurveyInquiryController.java, survwey/survwey/src/main/java/mcnc/survwey/api/survey/inquiry/service/SurveyInquiryService.java, survwey/survwey/src/main/java/mcnc/survwey/api/survey/manage/controller/SurveyManageController.java, survwey/survwey/src/main/java/mcnc/survwey/api/survey/manage/service/SurveyManageService.java, survwey/survwey/src/main/java/mcnc/survwey/domain/survey/repository/queryDSL/SurveyRepositoryCustom.java, survwey/survwey/src/main/java/mcnc/survwey/domain/survey/repository/queryDSL/SurveyRepositoryImpl.java
- 참여 가능 설문 검색 쿼리 수정
- 설문 수정 가능한지 확인 로직 조건 추가
=> fix: 쿼리 및 로직 오류 수정

survwey/survwey/src/main/java/mcnc/survwey/api/mail/controller/MailController.java, survwey/survwey/src/main/java/mcnc/survwey/api/mail/service/MailService.java, survwey/survwey/src/main/java/mcnc/survwey/global/exception/custom/ErrorCode.java, survwey/survwey/src/main/java/mcnc/survwey/global/utils/EncryptionUtil.java
- Controller 요청 형식 변경
- 요청 이메일 검증 로직 추가
- 요청 이메일 복호화 로직 추가
- 이메일 예외 처리 리펙토링
=> feat: 이메일 초대 로직 수정 및 리펙토링

survwey/survwey/src/main/java/mcnc/survwey/api/mail/service/MailService.java
- 병렬 스트림 사용 시 타임리프 Context가 Lock이 걸려 읽지 못하는 문제 해결
=> fix: 메일 전송 병렬 스트림 오류 해결

survwey/survwey/src/main/java/mcnc/survwey/api/mail/service/MailService.java, survwey/survwey/src/main/java/mcnc/survwey/domain/subjAnswer/repository/queryDSL/SubjAnswerRepositoryImpl.java, survwey/survwey/src/main/java/mcnc/survwey/global/config/SecurityConfig.java, survwey/survwey/src/main/java/mcnc/survwey/global/utils/EncryptionUtil.java
=> feat: webconfig 수정

survwey/survwey/src/main/java/mcnc/survwey/global/config/SecurityConfig.java
=> feat: CORS 수정

survwey/survwey/src/main/java/mcnc/survwey/api/survey/response/controller/SurveyResponseController.java, survwey/survwey/src/main/java/mcnc/survwey/api/survey/response/service/SurveyReplyService.java, survwey/survwey/src/main/java/mcnc/survwey/global/exception/custom/ErrorCode.java
-이메일 링크 클릭 시 응답한 설문 여부 확인 로직 작성
-errorCode: 409 - 이미 응답한 설문
-errorCode: 410 - 만료된 설문
-200 - 미응답 설문
=> feat: 이메일 링크 클릭 시 응답한 설문인지 확인 API 작성

survwey/survwey/src/main/java/mcnc/survwey/api/mail/service/MailService.java, survwey/survwey/src/main/java/mcnc/survwey/api/mail/utils/ThymeleafUtil.java, survwey/survwey/src/main/java/mcnc/survwey/api/survey/response/controller/SurveyResponseController.java, survwey/survwey/src/main/java/mcnc/survwey/api/survey/response/service/SurveyReplyService.java
-Context 중복되는 부분 ThymeleafUtil에서 초기화 하여 사용
=> refactor: MailService 구조 리팩토링

survwey/survwey/src/main/java/mcnc/survwey/api/mail/utils/ThymeleafUtil.java
=> refactor: ThymeleafUtil 구조 수정

survwey/survwey/src/main/java/mcnc/survwey/api/account/dto/PasswordModifyDTO.java, survwey/survwey/src/main/java/mcnc/survwey/api/account/dto/RegisterDTO.java, survwey/survwey/src/main/java/mcnc/survwey/api/auth/dto/LoginDTO.java, survwey/survwey/src/main/java/mcnc/survwey/api/survey/response/dto/result/QuestionResultDTO.java, survwey/survwey/src/main/java/mcnc/survwey/api/survey/response/service/AnsweredSurveyService.java, survwey/survwey/src/main/java/mcnc/survwey/api/survey/response/service/SurveyResultService.java, survwey/survwey/src/main/java/mcnc/survwey/domain/question/repository/queryDSL/QuestionRepositoryImpl.java
- 설문 결과 오류 수정(로직 변경)
- 비밀번호 유효성 검증 추가
=> fix: 설문 결과 오류 수정 및 비밀번호 유효성 검증 추가

survwey/survwey/src/main/java/mcnc/survwey/api/mail/service/MailService.java
=> fix: 메일 동시 전송 오류 수정

survwey/survwey/src/main/java/mcnc/survwey/domain/survey/repository/queryDSL/SurveyRepositoryImpl.java
=> fix: 쿼리 오류 수정

survwey/survwey/src/main/java/mcnc/survwey/api/account/service/AccountService.java, survwey/survwey/src/main/java/mcnc/survwey/api/mail/service/MailService.java
=> refactor: 프로필 수정 서비스 if 절 수정

survwey/survwey/src/main/java/mcnc/survwey/api/account/service/AccountService.java
=> feat: 프로필 수정 이메일 중복 검증 추가

survwey/survwey/src/main/java/mcnc/survwey/api/mail/service/MailService.java, survwey/survwey/src/main/java/mcnc/survwey/api/survey/response/service/AnsweredSurveyService.java, survwey/survwey/src/main/java/mcnc/survwey/api/survey/response/service/SurveyResultService.java, survwey/survwey/src/main/java/mcnc/survwey/domain/objAnswer/repository/queryDSL/ObjAnswerRepositoryCustom.java, survwey/survwey/src/main/java/mcnc/survwey/domain/question/repository/queryDSL/QuestionRepositoryCustom.java, survwey/survwey/src/main/java/mcnc/survwey/domain/subjAnswer/repository/queryDSL/SubjAnswerRepositoryCustom.java, survwey/survwey/src/main/java/mcnc/survwey/domain/survey/repository/queryDSL/SurveyRepositoryCustom.java
- MailService 빈 생성 시 타임리프 초기화하도록 수정
- QueryDSL 주석 작성
- 응답 Service 리펙토링
=> 빈 생성 시 초기화 로직 작성 및 리펙토링

survwey/survwey/src/main/java/mcnc/survwey/api/account/service/AccountService.java, survwey/survwey/src/main/java/mcnc/survwey/api/auth/controller/AuthController.java, survwey/survwey/src/main/java/mcnc/survwey/api/mail/service/MailService.java, survwey/survwey/src/main/java/mcnc/survwey/api/survey/response/controller/SurveyResponseController.java, survwey/survwey/src/main/java/mcnc/survwey/domain/question/service/QuestionService.java, survwey/survwey/src/main/java/mcnc/survwey/domain/selection/service/SelectionService.java, survwey/survwey/src/main/java/mcnc/survwey/domain/user/enums/Gender.java, survwey/survwey/src/main/java/mcnc/survwey/domain/user/service/UserService.java, survwey/survwey/src/main/java/mcnc/survwey/global/exception/custom/ErrorCode.java
=> fix: 충돌 해결, 전체 주석 추가, 코드 일부 수정

survwey/survwey/src/main/java/mcnc/survwey/SurvweyApplication.java, survwey/survwey/src/main/java/mcnc/survwey/api/mail/service/MailService.java, survwey/survwey/src/main/java/mcnc/survwey/api/mail/utils/ThymeleafUtil.java, survwey/survwey/src/main/java/mcnc/survwey/global/config/RedisConfig.java
- 설문 종료 알림 파라미터 이름 변경
- 설문 종료 알림 html 및 데이터 수정
=> feat: 설문 종료 알림 로직 데이터 수정 및 리펙토링

survwey/survwey/src/main/java/mcnc/survwey/api/survey/manage/service/SurveyManageService.java, survwey/survwey/src/main/resources/templates/mail/notification.html
- 설문 종료 html 문구 수정
- 설문 수정 체크 로직 순서 수정
=> fix: 설문 종료 html 및 설문 수정 체크 로직 수정

survwey/survwey/src/main/java/mcnc/survwey/api/mail/service/MailService.java, survwey/survwey/src/main/java/mcnc/survwey/api/survey/inquiry/dto/SurveyDTO.java, survwey/survwey/src/main/java/mcnc/survwey/api/survey/manage/controller/SurveyManageController.java, survwey/survwey/src/main/java/mcnc/survwey/api/survey/manage/dto/QuestionDTO.java, survwey/survwey/src/main/java/mcnc/survwey/domain/survey/service/SurveyService.java
- 설문 만료일 응답 코드 수정
- 설문 요청 글자 수 유효성 검사 추가
=> refactor: 설문 유효성 검사 추가 및 응답 코드 수정

survwey/survwey/src/main/java/mcnc/survwey/api/account/controller/AccountController.java, survwey/survwey/src/main/java/mcnc/survwey/api/account/service/AccountService.java, survwey/survwey/src/main/java/mcnc/survwey/api/mail/service/MailService.java, survwey/survwey/src/main/java/mcnc/survwey/api/survey/manage/controller/SurveyManageController.java, survwey/survwey/src/main/java/mcnc/survwey/api/survey/manage/service/SurveyManageService.java, survwey/survwey/src/main/java/mcnc/survwey/domain/question/repository/queryDSL/QuestionRepositoryImpl.java, survwey/survwey/src/main/java/mcnc/survwey/global/utils/DecryptionRequestBodyAdvice.java, survwey/survwey/src/main/java/mcnc/survwey/global/utils/EncryptionUtil.java, survwey/survwey/src/test/java/mcnc/survwey/user/service/AccountServiceTest.java
- 설문 결과 DB 쿼리 수정
- EmailService 로직 순서 및 이름 리펙토링
- 설문 종료 로직 유효성 검증 추가
- RequestBodyAdvice 주석 작성
=> refactor: 로직 순서 변경 및 리펙토링
